char otazky_ceny[][] =
{
	"Kolik $ ti zůstane pokud máš 3000$ a koupíš si glock?|2800$",
	"Kolik $ dostaneš za kill zeusem v MM?|0$",
	"Kolik $ ti zůstane pokud máš 5600$ a chceš si koupit negev?|5600$",
	"Kolik $ stojí Návnada(decoy)?|50$",
	"Kolik zaplatíš $ pokud si koupíš M4A1, 2x Flash, 1x Helma+Vesta, Defusky a Five-Seven?|5400$",
	"Kolik $ potřebuješ k zakoupení UMP45 + Deagle?|1900$",
	"Kolik $ stojí USP-S?|200$",
	"Kolik $ stojí Glock-18?|200$",
	"Kolik $ stojí P2000?|200$",
	"Kolik $ stojí Dual Berretas?|500$",
	"Kolik $ stojí Desert Eagle?|700$",
	"Kolik $ stojí Five-Seven?|500$",
	"Kolik $ stojí Tec-9?|500$",
	"Kolik $ stojí CZ-75a?|500$",
	"Kolik $ stojí P250?|300$",
	"Kolik $ stojí Nova?|1200$",
	"Kolik $ stojí Sawed-Off(upilovaná)?|1200$",
	"Kolik $ stojí M249?|5200$",
	"Kolik $ stojí Negev?|5700$",
	"Kolik $ stojí Mag-7?|1800$",
	"Kolik $ stojí MP9?|1250$",
	"Kolik $ stojí MP7?|1700$",
	"Kolik $ stojí UMP-45?|1200$",
	"Kolik $ stojí P90?|2350$",
	"Kolik $ stojí Bizon?|1400$",
	"Kolik $ stojí Mac-10?|1050$",
	"Kolik $ stojí Galil?|2000$",
	"Kolik $ stojí AK-47?|2700$",
	"Kolik $ stojí SSG-08(scout)?|1700$",
	"Kolik $ stojí SG-556?|3000$",
	"Kolik $ stojí AWP?|4750$",
	"Kolik $ stojí G3SG1?|5000$",
	"Kolik $ stojí Famas?|2250$",
	"Kolik $ stojí M4A4?|3100$",
	"Kolik $ stojí M4A1-S?|3100$",
	"Kolik $ stojí AUG?|3300$",
	"Kolik $ stojí Scar-20?|5000$",
};
char otazky_puvody[][] =
{
	"Z které země pochází zbraň USP-S?|Německo",
	"Z které země pochází zbraň Dual Berettas?|Itálie",
	"Z které země pochází zbraň Desert Eagle?|Izrael",
	"Z které země pochází zbraň Five-Seven?|Belgie",
	"Z které země pochází zbraň Tec-9?|USA/Švédsko",
	"Z které země pochází zbraň CZ-75?|Česko",
	"Z které země pochází zbraň P250?|Německo/Švýcarsko",
	"Z které země pochází zbraň Glock-18?|Nizozemsko",
	"Z které země pochází zbraň Nova?|Itálie",
	"Z které země pochází zbraň XM1014?|Itálie",
	"Z které země pochází zbraň Sawed-Off?|USA",
	"Z které země pochází zbraň M249?|Belgie",
	"Z které země pochází zbraň Nagev?|Izrael",
	"Z které země pochází zbraň MAG-7?|Jižní Afrika",
	"Z které země pochází zbraň MP9?|Švýcarsko",
	"Z které země pochází zbraň MP7?|Německo",
	"Z které země pochází zbraň UMP-45?|Německo",
	"Z které země pochází zbraň P90?|Belgie",
	"Z které země pochází zbraň PP-Bizon?|Rusko",
	"Z které země pochází zbraň Mac-10?|USA",
	"Z které země pochází zbraň Galil AR?|Izrael",
	"Z které země pochází zbraň AK-47?|Rusko",
	"Z které země pochází zbraň SSG 08?|Nizozemsko",
	"Z které země pochází zbraň SG 553?|Švýcarsko",
	"Z které země pochází zbraň AWP?|Velká Británie",
	"Z které země pochází zbraň G3SG1?|Německo",
	"Z které země pochází zbraň Famas?|Francie",
	"Z které země pochází zbraň M4A4?|USA",
	"Z které země pochází zbraň M4A1-S?|USA",
	"Z které země pochází zbraň AUG?|Nizozemsko",
	"Z které země pochází zbraň SCAR-20?|Belgie/USA",
};
char otazky_vseobecne[][] =
{
	"Po které verzi Counter-Striku byl vydán Counter-Strike Source?|Counter-Strike: Condition Zero",
	"V jakém roce vyšel Counter-Strike 1.6|2003",
	"Co znamená zkratka HE|High Explosive nebo vysoce výbušný",
	"Na jakem 'enginu' běží Counter-Strike Global Offsensive|Source Engine",
	"Kdo založil firmu Valve?|Gabe Newell",
	"V kterém roce byla vydána hra Counter-Strike: Global Offensive?|2012",
	"Podle koho se jmenují BOTi ve hře CS:GO?|Podle zaměstnanců Valve",
	"Co znamená zkratka VAC?|Valve Anti Cheat",
};
char otazky_mesta[][] =
{
	"Jaké je hlavní město státu Austrálie?|Canberra",
	"Jaké je hlavní město státu Bělorusko?|Minsk",
	"Jaké je hlavní město státu Česká Republika?|Praha",
	"Jaké je hlavní město státu Dánsko?|Kodaň",
	"Jaké je hlavní město státu Čína?|Peking",
	"Jaké je hlavní město státu Egypt?|Káhira",
	"Jaké je hlavní město státu Ekvádor?|Quito",
	"Jaké je hlavní město státu Francie?|Paříž",
	"Jaké je hlavní město státu Irák?|Bagdád",
	"Jaké je hlavní město státu Izrael?|Jeruzalém",
	"Jaké je hlavní město státu Japonsko?|Tokio",
	"Jaké je hlavní město státu Kanada?|Ottawa",
	"Jaké je hlavní město státu Katar?|Dauhá",
	"Jaké je hlavní město státu Keňa?|Nairobi",
	"Jaké je hlavní město státu Laos?|Vientiane",
	"Jaké je hlavní město státu Libye?|Tripolis",
	"Jaké je hlavní město státu Madagaskar?|Antananarivo",
	"Jaké je hlavní město státu Maďarsko?|Budapešť",
	"Jaké je hlavní město státu Německo?|Berlín",
	"Jaké je hlavní město státu Slovensko?|Bratislava",
	"Jaké je hlavní město státu Ruská Federace?|Moskva",
	"Jaké je hlavní město státu Nigerie?|Abuja",
	"Jaké je hlavní město státu Nový Zéland?|Wellington",
	"Jaké je hlavní město státu Norsko?|Oslo",
	"Jaké je hlavní město státu Rakousko?|Vídeň",
	"Jaké je hlavní město státu Singapur?|Singapur",
	"Jaké je hlavní město státu Španělsko?|Madrid",
	"Jaké je hlavní město státu Italie?|Řím",
	"Jaké je hlavní město státu Litva?|Vilnius",
	"Jaké je hlavní město státu Pobřeží slonoviny?|Yamoussoukro",
	"Jaké je hlavní město státu Polsko?|Varšava",
};
